server:
  port:

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://域名:端口号/数据库名?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
    username:
    password:
    hikari:
      # 连接池空闲连接的最小数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认 600000（ 10 分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是 10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为，默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: hikariDataSource
      # 此属性控制池中连接的最长生命周期，值 0 表示无限生命周期，默认 1800000，即 30 分钟
      max-lifetime: 1800000
      # 数据库连接超时时间，默认 30 秒，即 30000
      connection-timeout: 30000
  redis:
    host:
    port:
  elasticsearch:
    uris:
  # mq配置
  rabbitmq:
    host: 你的ip
    port: 5672
    username: rabbitmq用户名
    password: rabbitmq密码
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3 #最大重试次数
          initial-interval: 3000 #重试间隔时间（单位毫秒）

blog:
  asynchronous:
    core-pool-size: 10
    max-pool-size: 20
    keep-alive-seconds: 30
    queue-capacity: 15
    await-for-tasks-to-complete-on-shutdown: true
    await-termination-seconds: 30
  upload:
    strategy: cos
    local:
      upload-url:
      access-url:
    oss:
      access-url:
      endpoint:
      bucket-name:
      access-key-id:
      access-key-secret:
    cos:
      access-url:
      region:
      bucket-name:
      secret-id:
      secret-key:

search:
  mode: mysql

qq:
  app-id: QQ APPID
  check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
  user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}

weibo:
  app-id: 微博APPID
  app-secret: 微博APPSECRET
  grant-type: authorization_code
  redirect-url: 微博回调地址
  access-token-url: https://api.weibo.com/oauth2/access_token
  user-info-url: https://api.weibo.com/2/users/show.json?uid={uid}&access_token={access_token}

website:
  url: http://你的主域名或ip

